import { createFileRoute, Link } from "@tanstack/react-router";
import type { ComponentType, ReactNode } from "react";
import {
  IconArrowLeft,
  IconBrandGithub,
  IconBrandLinkedin,
  IconBrandTelegram,
  IconDownload,
  IconMail,
  IconMapPin,
  IconWorld,
} from "@tabler/icons-react";
import { Button } from "@/components/ui/button";
import { createResumeMeta } from "@/lib/seo";
// Generated by ~/growth/me/resume/export-site.ts from the same data as the PDF. Edit it there.
import resume from "@/data/resume.json";

export const Route = createFileRoute("/resume")({
  component: ResumePage,
  head: () =>
    createResumeMeta({ description: `${resume.name} - ${resume.headline}. ${resume.location}.` }),
});

const ICONS: Record<string, ComponentType<{ className?: string }>> = {
  email: IconMail,
  site: IconWorld,
  github: IconBrandGithub,
  linkedin: IconBrandLinkedin,
  telegram: IconBrandTelegram,
};

const LINK = "underline decoration-foreground/30 underline-offset-2 hover:decoration-foreground";

// Bare domains in the text ("sportmagaz.com.ua", "danolekh.com/p/oasi-kadir") become links, like
// in the PDF. Links to this site stay on it.
const DOMAIN = /\b((?:[a-z0-9-]+\.)+(?:com|io|dev|app|website)(?:\.ua)?(?:\/[\w\-./#?=&]*)?)/g;
function linkify(text: string): ReactNode[] {
  const out: ReactNode[] = [];
  let last = 0;
  for (const m of text.matchAll(DOMAIN)) {
    const at = m.index ?? 0;
    out.push(text.slice(last, at));
    const href = m[1].startsWith("danolekh.com")
      ? m[1].slice("danolekh.com".length) || "/"
      : `https://${m[1]}`;
    out.push(
      <a key={at} href={href} className={LINK}>
        {m[1]}
      </a>,
    );
    last = at + m[0].length;
  }
  out.push(text.slice(last));
  return out;
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="border-t border-dashed pt-6 print:pt-3">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
        {title}
      </h2>
      <div className="mt-4 print:mt-2">{children}</div>
    </section>
  );
}

function ResumePage() {
  return (
    <div className="min-h-dvh px-6 py-12 print:p-0">
      <div className="mx-auto max-w-3xl">
        <Button
          render={<Link to="/"></Link>}
          nativeButton={false}
          variant="link"
          className="px-0 print:hidden"
        >
          <IconArrowLeft />
          Back home
        </Button>

        <header className="mt-6 print:mt-0">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div className="min-w-0">
              <h1 className="text-3xl font-semibold tracking-tight text-foreground lg:text-4xl">
                {resume.name}
              </h1>
              <p className="mt-1 text-lg text-muted-foreground">{resume.headline}</p>
            </div>
            <Button
              render={<a href={resume.pdf} download="Dan-Olekh-Resume.pdf"></a>}
              nativeButton={false}
              variant="outline"
              className="print:hidden"
            >
              <IconDownload />
              Download PDF
            </Button>
          </div>

          <ul className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground">
            <li className="inline-flex items-center gap-1.5">
              <IconMapPin className="size-4 shrink-0" />
              {resume.location}
            </li>
            {resume.contacts.map((c) => {
              const Icon = ICONS[c.kind] ?? IconWorld;
              return (
                <li key={c.kind} className="min-w-0">
                  <a
                    href={c.href}
                    className="inline-flex items-center gap-1.5 break-all hover:text-foreground"
                  >
                    <Icon className="size-4 shrink-0" />
                    {c.label}
                  </a>
                </li>
              );
            })}
          </ul>

          <p className="mt-6 leading-relaxed text-foreground/90">{resume.summary}</p>
        </header>

        <div className="mt-8 space-y-8 print:mt-4 print:space-y-4">
          <Section title="Experience">
            <ol className="space-y-7 print:space-y-3">
              {resume.experience.map((role) => (
                <li key={`${role.company}-${role.dates}`} className="break-inside-avoid">
                  <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-0.5">
                    <p className="font-medium text-foreground">
                      {role.title} <span className="text-muted-foreground">·</span> {role.company}
                    </p>
                    <p className="text-sm tabular-nums text-muted-foreground">
                      {role.dates}
                      {role.where ? ` · ${role.where}` : ""}
                    </p>
                  </div>
                  <ul className="mt-2 list-disc space-y-1.5 pl-5 leading-relaxed text-foreground/90 marker:text-muted-foreground">
                    {role.bullets.map((b) => (
                      <li key={b}>{linkify(b)}</li>
                    ))}
                  </ul>
                </li>
              ))}
            </ol>
          </Section>

          <Section title="Projects">
            <ul className="space-y-2 leading-relaxed text-foreground/90">
              {resume.projects.map((p) => (
                <li key={p.name}>
                  <span className="font-medium text-foreground">{p.name}</span>
                  {p.link ? (
                    <>
                      {" ("}
                      <a href={`https://${p.link}`} className={LINK}>
                        {p.link}
                      </a>
                      {")"}
                    </>
                  ) : null}
                  : {linkify(p.text)}
                </li>
              ))}
            </ul>
          </Section>

          <Section title="Open source">
            <ul className="space-y-2 leading-relaxed text-foreground/90">
              {resume.openSource.map((o) => (
                <li key={o.name}>
                  <span className="font-medium text-foreground">{o.name}</span>, {linkify(o.text)}
                </li>
              ))}
            </ul>
          </Section>

          <Section title="Skills">
            <dl className="space-y-3 sm:grid sm:grid-cols-[7rem_minmax(0,1fr)] sm:gap-x-6 sm:gap-y-3 sm:space-y-0">
              {resume.skills.map((s) => (
                <div key={s.area} className="sm:contents">
                  <dt className="text-xs uppercase tracking-wide text-muted-foreground sm:pt-1">
                    {s.area}
                  </dt>
                  <dd className="leading-relaxed text-foreground/90">{s.items}</dd>
                </div>
              ))}
            </dl>
          </Section>

          <div className="grid gap-8 sm:grid-cols-2 print:grid-cols-2 print:gap-4">
            <Section title="Education">
              <p className="leading-relaxed text-foreground/90">{resume.education}</p>
            </Section>
            <Section title="Languages">
              <p className="leading-relaxed text-foreground/90">{resume.languages}</p>
            </Section>
          </div>
        </div>
      </div>
    </div>
  );
}
