/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FeedRouteRouteImport } from './routes/feed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as BIndexRouteImport } from './routes/b.index'
import { Route as PProjectRouteImport } from './routes/p.$project'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as ApiBooksRouteImport } from './routes/api/books'
import { Route as FeedBBookIdRouteImport } from './routes/feed_.b.$bookId'
import { Route as FeedBBookIdModalRouteImport } from './routes/feed/b/$bookId/modal'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRouteRoute = FeedRouteRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const BIndexRoute = BIndexRouteImport.update({
  id: '/b/',
  path: '/b/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectRoute = PProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksRoute = ApiBooksRouteImport.update({
  id: '/api/books',
  path: '/api/books',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedBBookIdRoute = FeedBBookIdRouteImport.update({
  id: '/feed_/b/$bookId',
  path: '/feed/b/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedBBookIdModalRoute = FeedBBookIdModalRouteImport.update({
  id: '/b/$bookId/modal',
  path: '/b/$bookId/modal',
  getParentRoute: () => FeedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/books': typeof ApiBooksRoute
  '/b/$slug': typeof BSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/p/$project': typeof PProjectRoute
  '/b/': typeof BIndexRoute
  '/lab/': typeof LabIndexRoute
  '/feed/b/$bookId': typeof FeedBBookIdRoute
  '/feed/b/$bookId/modal': typeof FeedBBookIdModalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/books': typeof ApiBooksRoute
  '/b/$slug': typeof BSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/p/$project': typeof PProjectRoute
  '/b': typeof BIndexRoute
  '/lab': typeof LabIndexRoute
  '/feed/b/$bookId': typeof FeedBBookIdRoute
  '/feed/b/$bookId/modal': typeof FeedBBookIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/books': typeof ApiBooksRoute
  '/b/$slug': typeof BSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/p/$project': typeof PProjectRoute
  '/b/': typeof BIndexRoute
  '/lab/': typeof LabIndexRoute
  '/feed_/b/$bookId': typeof FeedBBookIdRoute
  '/feed/b/$bookId/modal': typeof FeedBBookIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/api/books'
    | '/b/$slug'
    | '/lab/$slug'
    | '/p/$project'
    | '/b/'
    | '/lab/'
    | '/feed/b/$bookId'
    | '/feed/b/$bookId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/api/books'
    | '/b/$slug'
    | '/lab/$slug'
    | '/p/$project'
    | '/b'
    | '/lab'
    | '/feed/b/$bookId'
    | '/feed/b/$bookId/modal'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/api/books'
    | '/b/$slug'
    | '/lab/$slug'
    | '/p/$project'
    | '/b/'
    | '/lab/'
    | '/feed_/b/$bookId'
    | '/feed/b/$bookId/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRouteRoute: typeof FeedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBooksRoute: typeof ApiBooksRoute
  BSlugRoute: typeof BSlugRoute
  LabSlugRoute: typeof LabSlugRoute
  PProjectRoute: typeof PProjectRoute
  BIndexRoute: typeof BIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  FeedBBookIdRoute: typeof FeedBBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/': {
      id: '/b/'
      path: '/b'
      fullPath: '/b/'
      preLoaderRoute: typeof BIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project': {
      id: '/p/$project'
      path: '/p/$project'
      fullPath: '/p/$project'
      preLoaderRoute: typeof PProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books': {
      id: '/api/books'
      path: '/api/books'
      fullPath: '/api/books'
      preLoaderRoute: typeof ApiBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed_/b/$bookId': {
      id: '/feed_/b/$bookId'
      path: '/feed/b/$bookId'
      fullPath: '/feed/b/$bookId'
      preLoaderRoute: typeof FeedBBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/b/$bookId/modal': {
      id: '/feed/b/$bookId/modal'
      path: '/b/$bookId/modal'
      fullPath: '/feed/b/$bookId/modal'
      preLoaderRoute: typeof FeedBBookIdModalRouteImport
      parentRoute: typeof FeedRouteRoute
    }
  }
}

interface FeedRouteRouteChildren {
  FeedBBookIdModalRoute: typeof FeedBBookIdModalRoute
}

const FeedRouteRouteChildren: FeedRouteRouteChildren = {
  FeedBBookIdModalRoute: FeedBBookIdModalRoute,
}

const FeedRouteRouteWithChildren = FeedRouteRoute._addFileChildren(
  FeedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRouteRoute: FeedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBooksRoute: ApiBooksRoute,
  BSlugRoute: BSlugRoute,
  LabSlugRoute: LabSlugRoute,
  PProjectRoute: PProjectRoute,
  BIndexRoute: BIndexRoute,
  LabIndexRoute: LabIndexRoute,
  FeedBBookIdRoute: FeedBBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
